version: 2
jobs:
  build1:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Chrome 1
          command: build.sh 1
workflows:
  version: 2
  build_all:
    jobs:
      - build1
